# Generated by Django 4.2.16 on 2025-01-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_fisioterapeuta_modalidades_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.BooleanField(choices=[(True, 'Pago'), (False, 'Pendente')], default=False),
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('status', models.BooleanField(choices=[(True, 'Pago'), (False, 'Pendente')], default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.matricula')),
            ],
        ),
    ]
