# Generated by Django 4.2.16 on 2025-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_matricula_data_pagamento_matricula_status_pagamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='matricula',
            name='dia_pagamento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='dias_semana',
            field=models.CharField(blank=True, choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100),
        ),
        migrations.AddField(
            model_name='matricula',
            name='horario_aula',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
