# Generated by Django 4.2.16 on 2025-01-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_matricula_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='dias_semana',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
