# Generated by Django 4.2.16 on 2025-01-07 19:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_matricula_dias_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='dias_semana',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=False),
        ),
    ]
