# Generated by Django 4.2.16 on 2025-01-10 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_matricula_dias_semana_alter_matricula_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='mes_referencia',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='data_pagamento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
