# Generated by Django 4.2.16 on 2025-01-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_pagamentos_mes_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='ano_referencia',
            field=models.IntegerField(default=2025),
        ),
    ]
