# Generated by Django 4.2.16 on 2025-01-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_fisioterapeuta_email_fisioterapeuta_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapeuta',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
