version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: fisioterapia_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root@123
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: ./fisioterapia_api
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./fisioterapia_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
  
  frontend:
    build:
      context: ./cliente-pwa
      dockerfile: Dockerfile
    command: >
      sh -c "npm install && npm start"
    ports:
      - "3000:3000"  # Porta do React em desenvolvimento
    volumes:
      - ./cliente-pwa:/app
      - /cliente-pwa/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - app-network
    depends_on:
      - web

networks:
  app-network:
    driver: bridge